My_Second_Project/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

app_name='Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/',views.register, name='register'),
    path('login/',views.login_page,name='login'),
    path('user_login/',views.user_login,name='user_login'),
    path('user_logout/',views.user_logout,name='logout'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField (upload_to = 'profile_pics', blank=True)

def  __str__(self):
    return self.UserInfo.user

My_Second_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo


class UserForm (forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','password','email')

class UserInfoForm (forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id','profile_pic')

My_Second_Project/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm,UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User
# Create your views here.


def login_page(request):
    return render(request, 'Login_app/login.html', context={})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse ('User not Active')
        else:
            return HttpResponse('Login information is not correct')
    else:
        # return render(request, 'Login_app/login.html',context={})
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

def index(request):
    dict={}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict={'user_basic_info':user_basic_info, 'user_more_info':user_more_info}
    return render(request, 'Login_app/index.html', context=dict)

def  __str__(self):
    return self.User.username
def  __str__(self):
    return self.UserInfo.user

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True

    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()
    dict = {'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered}
    return render(request,'Login_app/register.html',context=dict)

My_Second_Project/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>{{ title }}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Login_app:register' %}">User Registration</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </nav>
    <div class="container" style="padding-top:20px">
      {% block body_block %}

      {% endblock %}
    </div>

</body>
</html>

My_Second_Project/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}

{% block body_block %}
{% if user.is_authenticated %}
<p>{{user_basic_info.username}}</p>
<p>{{user_basic_info.email}}</p>
<p><a href="{{user_more_info.facebook_id}}">Facebook id</a></p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" alt="">
{% else %}
<div class="alert alert-primary">
  You are not logged in!!
</div>
{% endif %}
{% endblock %}

My_Second_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}

{% block body_block %}

<form class="" action="{% url 'Login_app:user_login' %}" method="POST">
  <label for="username">UserName</label>
  <input type="text" class="form-control" name="username" value="" placeholder="Enetr Username" required>
  <label for="password">Password</label>
  <input type="password" class="form-control" name="password" value="" placeholder="Enetr password" required>
  {% csrf_token %}
  <br>
  <input type="submit" name="submit" value="Login" class="btn btn-primary">
</form>

{% endblock %}

My_Second_Project/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}

{% if registered %}
<div class="alert alert-success">
  Congratulations! Registered Successfull.
</div>
{% else %}
<form enctype="multipart/form-data" method="POST">
  {{user_form.as_p}}
  {{user_info_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="User Registration">
</form>
{% endif %}
{% endblock %}